" 1. Functional settings
" 2. Interface settings
" 3. Visual settings

" 1. Functional settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" We're not vi
set nocompatible
set modelines=0

" Increase command history
set history=1000

" Autoupdate a file if it's changed from outisde
set autoread

" pwd should be the pwd of the file
set autochdir

" Show mode and cmd
set showmode
set showcmd

" Disable backups
set nobackup
set nowritebackup
set noswapfile

" Return to normal mode when focus is lost
if has('autocmd')
    au FocusLost * call feedkeys("\<C-\>\<C-n>")
endif

" UTF-8 is the only format
set encoding=utf-8

set backspace=2

" Language-specific
filetype on
filetype plugin indent on
if has('autocmd')

    au BufRead,BufNewFile *.less set filetype=less
    au BufRead,BufNewFile *.json set ft=javascript
    "au BufNewFile,BufRead *gitconfig setf gitconfig
    au BufRead,BufNewFile Vagrantfile set filetype=ruby
    au BufRead,BufNewFile *.tac set ft=python
    "au BufRead,BufNewFile *.j2 set ft=jinja
    "au BufRead,BufNewFile *.ferm set ft=ferm

    au FileType jinja source ~/.vim/syntax/jinja.vim
    "if has('spell')
    "    au BufNewFile,BufRead COMMIT_EDITMSG setlocal spell
    "    au BufNewFile,BufRead *.asciidoc setlocal spell
    "endif

    " Git commits go to top of line and into insert mode
    "au BufNewFile,BufRead COMMIT_EDITMSG call feedkeys('ggi', 't')

endif

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

" 2. Interface Settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Split in the correct direction
set splitbelow
set splitright

" Mouse support
if has('mouse')
   set mouse=a
   set mousehide
endif

" Indenting
filetype indent on
set autoindent smartindent " Auto-indent
set smarttab " Better tab
set expandtab " Tabbed indent by default (overridden at times)
set copyindent preserveindent " Preserve indent structure
set softtabstop=2 " No spaces when tabbing
set shiftwidth=2 " Two characters wide when using >> and stuff
set tabstop=2 " Tabs count for 2 spaces
set shiftround " Indent as multiple of tab width

" Searching
" Use normal regex for searching
nnoremap / /\v
vnoremap / /\v
set ignorecase " Ignore case when searching...
set smartcase " ...unless there are caps.
set incsearch " Incremental search
set hlsearch " Highlight matches
set gdefault " Assume global search
set showmatch " Select breaches

" Clean up search by hitting space
noremap <leader><space> :noh<cr>

" Use tab instead of % for braces
nnoremap <tab> %
vnoremap <tab> %

" 3. Visual Settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Enable/Disable relativenumber, rule, cursorline and list for copys
map <F12> :set relativenumber! ruler! cursorline! list!<cr>

" Print ruler, cursorline and relative linenumbers
set relativenumber
set ruler
set cursorline

" Scroll 7 lines away from margins
set scrolloff=7

" Tabs and EOLs should look like TextMate
set list
set listchars=tab:▸\ ,eol:¬

" Soft wrap by word
set wrap " Enable wraping
set linebreak " Don't breake in the middle of words
set textwidth=0
set wrapmargin=0 " Breake the line before reaching the end of the window

" Line height shout be 1
set linespace=1

" Statusline
"if has('statusline')
    "set statusline=File:\ %.20F
    set statusline=File:\ %-10F\ %-2m\ %-10r\ FileType:\ %-4y
    "set statusline=\ %F " Filename + is modified
    "set statusline+=\ %m " Has the file been modified?
    "set statusline+=\ %r " Is the file read-only?
    "set statusline+=\ %h " Is this a help file?
    set statusline+=%= " Separator
    "set statusline+=\ -\      " Separator
    "set statusline+=FileType:\ %4y " Label
    "set statusline+=%y        " Filetype of the file
    "set statusline+=\ -\       " Separator
    "set statusline+=%c,\ " What column number?
    set statusline+=Character:\ %-4c\ Line:\ %-4l\ Total:\ %-4L
    "set statusline+=%l/%L\ " How far into the file are we?
    set laststatus=2 " Show the statusline in 2+ windows
"endif

" No error bells nor visual alerts
set noerrorbells
set visualbell t_vb=

" Syntax highlighting
set t_Co=256
if has('syntax')
    syntax on
endif

set background=dark
